version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chatgramm-backend
    ports:
      - "3002:3002"
    networks:
      - dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chatgramm-frontend
    ports:
      - "3000:3000"
    networks:
      - dev

networks:
  dev:
