version: '3.8'

networks:
  chat-gramm:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: chatgramm-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/server.crt:/etc/ssl/certs/server.crt:ro
      - /etc/ssl/private/server.key:/etc/ssl/private/server.key:ro
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "4443:443"
    networks:
      - chat-gramm
  postgres:
    image: postgres:latest
    container_name: chatgramm-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - chat-gramm

  backend:
    build: ./server
    container_name: chatgramm-backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      CLIENT_HOST: ${CLIENT_HOST}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - chat-gramm
    ports:
      - "3002:3002"

  frontend:
    build: ./client
    container_name: chatgramm-frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}

    networks:
      - chat-gramm
    ports:
      - "3000:3000"

volumes:
  postgres_data:
